image: fedora/latest
packages:
  - dotnet
sources:
  - https://git.sr.ht/~jkcclemens/NoSoliciting
secrets:
  - 92fe0dd0-db40-41e0-903a-a18489f75548
tasks:
  - build: |
      cd NoSoliciting/NoSoliciting.Trainer
      dotnet build -c Release
  - test: |
      cd NoSoliciting/NoSoliciting.Trainer
      ./bin/Release/net5/NoSoliciting.Trainer test data.csv
  - create-model: |
      cd NoSoliciting/NoSoliciting.Trainer
      ./bin/Release/net5/NoSoliciting.Trainer create-model data.csv
  - update-model: |
      cd NoSoliciting
      LAST_COMMIT=$(ssh -o 'StrictHostKeyChecking=accept-new' actions@warm.kitteh.space model commit)
      if [ "$LAST_COMMIT" = 'None' ] || git diff-tree --no-commit-id --name-only -r "$LAST_COMMIT"..HEAD | grep '^NoSoliciting\.Trainer/data\.csv'; then
          ssh actions@warm.kitteh.space model update < NoSoliciting.Trainer/model.zip
      fi
artifacts:
  - NoSoliciting/NoSoliciting.Trainer/model.zip
