image: fedora/latest
packages:
  - dotnet
  - wget
  - unzip
sources:
  - https://git.sr.ht/~jkcclemens/NoSoliciting
secrets:
  - 92fe0dd0-db40-41e0-903a-a18489f75548
tasks:
  - download-dalamud: |
      mkdir dalamud
      cd dalamud
      wget https://github.com/goatcorp/dalamud-distrib/raw/main/latest.zip
      unzip latest.zip
      rm latest.zip
  - build-plugin: |
      cd NoSoliciting/NoSoliciting
      dotnet build -c Release -p:IsCI=true
  - build-trainer: |
      cd NoSoliciting/NoSoliciting.Trainer
      dotnet build -c Release
  - test: |
      cd NoSoliciting/NoSoliciting.Trainer
      ./bin/Release/net5/NoSoliciting.Trainer test data.csv
  - create-model: |
      cd NoSoliciting/NoSoliciting.Trainer
      ./bin/Release/net5/NoSoliciting.Trainer create-model data.csv
  - update-model: |
      cd NoSoliciting
      LAST_COMMIT=$(ssh -o 'StrictHostKeyChecking=accept-new' actions@warm.kitteh.space model commit)
      if [ "$LAST_COMMIT" = 'None' ] || git diff-tree --no-commit-id --name-only -r "$LAST_COMMIT"..HEAD | grep '^NoSoliciting\.Trainer/data\.csv'; then
          ssh actions@warm.kitteh.space model update "$(git rev-parse HEAD)" < NoSoliciting.Trainer/model.zip
      fi
artifacts:
  - NoSoliciting/NoSoliciting/bin/Release/net5-windows/NoSoliciting/latest.zip
  - NoSoliciting/NoSoliciting.Trainer/model.zip
