name: Deploy Plugin

on:
  workflow_dispatch:
    inputs:
      deployment_type:
        default: 'stable'
        required: true
        type: string
        description: 'stable or testing'
      version:
        required: true
        description: 'version (e.g. 1.0.0.0)'
        type: string

jobs:
  deploy-plugin:
    uses: kalilistic/DalamudPluginDeploy/.github/workflows/deploy_plugin.yml@master
    with:
      public_name: "NoSoliciting"
      internal_name: "NoSoliciting"
      project_dir: "NoSoliciting"
      project_name: "NoSoliciting"
      github_username: "kalilistic"
      github_email: "35899782+kalilistic@users.noreply.github.com"
      open_pr: false
      deployment_type: ${{ github.event.inputs.deployment_type }}
      version: ${{ github.event.inputs.version }}
    secrets:
      DEPLOY_TOKEN: ${{ secrets.PAT }}
